version: '3.4'

networks:
  dev:
    driver: bridge

services:
  demo-app:
    depends_on:
      - "app_db"
    container_name: api-compose
    ports:
      - "6677:5062"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__PostgresqlConnection=User ID=postgres;Password=sanvalero12;Server=app_db;Port=5432;Database=BaseDeDatosPrueba; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:5062
    networks:
      - dev
  app_db:
    image: postgres
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sanvalero12
      - POSTGRES_DB=BaseDeDatosPrueba
    ports:
      - 7766:5432
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
      - ./database:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:

